# CICD using GitHub actions

name: CI/CD

# Exclude the workflow to run on changes to the helm chart and k8s manifests
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go 1.22
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Build the Go application
      run: go build -o joshnspire-web-app

    - name: Run tests
      run: go test ./...
  
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.56.2
  
  push:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/joshnspire-web-app:${{ github.run_id }}

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Update Docker image tag in Helm values.yaml
      run: |
        sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' helm/joshnspire-web-app-chart/values.yaml

    - name: Commit and Push updated Helm chart
      run: |
        git config --global user.email "joshua.veeraiah@example.com"
        git config --global user.name "Joshua Veeraiah"
        git add helm/joshnspire-web-app-chart/values.yaml
        git commit -m "Update Docker image tag in Helm chart"
        git push
